### Write a Python Program to Add Two Matrices?
Matrices of same order can be added

In [10]:
m1=[[1,2,5],[3,9,8],[5,7,3]]
m2=[[-7,4,8],[1,8,3],[4,6,-5]]
result=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(m1)):
    for j in range(len(m1[i])):
        result[i][j]=m1[i][j]+m2[i][j]
print("The sum of \n {} \n and \n{}\n is: \n {}".format(m1,m2,result))

The sum of 
 [[1, 2, 5], [3, 9, 8], [5, 7, 3]] 
 and 
[[-7, 4, 8], [1, 8, 3], [4, 6, -5]]
 is: 
 [[-6, 6, 13], [4, 17, 11], [9, 13, -2]]


In [31]:
import numpy as np
m1=np.array([[1,2,5],[3,9,8],[5,7,3]])
m2=np.array([[-7,4,8],[1,8,3],[4,6,-5]])
result=np.add(m1,m2)
print(result)

[[-6  6 13]
 [ 4 17 11]
 [ 9 13 -2]]


### Write a Python Program to Multiply Two Matrices?
Two matrices of the type m x n and n x p can be multiplied i.e. no. of rows of one matrix is equal to no. of rows of another

In [14]:
m1=[[1,2,5,4],[3,9,8,-4],[5,7,3,2]] #3x4
m2=[[-7,4,8],[1,8,3],[4,6,-5],[5,2,-2]]  #4x3
result=[[0,0,0],[0,0,0],[0,0,0]] #result is 3x3
for i in range(len(m1)):
    for j in range(len(m2[i])):
        for k in range(len(m2)):
            result[i][j]+=m1[i][k]*m2[k][j]
print(result)


[[35, 58, -19], [0, 124, 19], [-6, 98, 42]]


In [32]:
m1=np.array([[1,2,5,4],[3,9,8,-4],[5,7,3,2]]) #3x4
m2=np.array([[-7,4,8],[1,8,3],[4,6,-5],[5,2,-2]])  #4x3
result=np.dot(m1,m2)
print(result)

[[ 35  58 -19]
 [  0 124  19]
 [ -6  98  42]]


### Write a Python Program to Transpose a Matrix?

In [17]:
m1=[[1,2,5,4],
    [3,9,8,-4],
    [5,7,3,2]]
result=[[0,0,0],
        [0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(m1)):
    for j in range(len(m1[i])):
        result[j][i]=m1[i][j]
print(result)

[[1, 3, 5], [2, 9, 7], [5, 8, 3], [4, -4, 2]]


In [35]:
m1=np.array([[1,2,5,4],
    [3,9,8,-4],
    [5,7,3,2]])
print(m1.transpose())

[[ 1  3  5]
 [ 2  9  7]
 [ 5  8  3]
 [ 4 -4  2]]


### Write a Python Program to Sort Words in Alphabetic Order?

In [25]:
str = input("Enter some string: ")
str=str.lower()
words = str.split()
words.sort()
for word in words:
    print(word)

Enter some string: This is full stack data science assignment
assignment
data
full
is
science
stack
this


### Write a Python Program to Remove Punctuation From a String?

In [28]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
str=input("Enter text to remove punctuations: ")
str1=""
for i in str:
    if i not in punctuations:
        str1=str1+i
print("String after punctuations are removed is: ",str1)

Enter text to remove punctuations: Punctuations to remove !a()b-cf[]g{}g;:'gh"\j,<>./?@#$%^&*_~
String after punctuations are removed is:  Punctuations to remove abcfggghj
